version: '3'

services:
  website:
    image: slimtest
    volumes:
      - ./:/var/www/html
    ports:
      - 5000:80
    links:
      - db

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 5001:3306