version: '3'

services:
  website:
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - 5013:80
    links:
      - db

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 5012:3306